# Generated by Django 2.2.5 on 2019-09-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='Nome do departamento', max_length=200),
        ),
    ]
